# docker-compose.yaml
version: '3'

services :
  php:
    container_name: php.plb 
    build:
      context: ./
      dockerfile: Dockerfile-php
    depends_on:
      - mariadb
    volumes:
      - ./docker/.env.local:/var/www/.env.local
      - ${PLB_REPO}:/var/www
    environment:
      APP_ENV: dev
    working_dir: /var/www

  nginx:
    container_name: nginx.plb
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./docker/planningbiblio.conf:/etc/nginx/conf.d/default.conf
      - ./docker/.env.local:/var/www/.env.local
      - ${PLB_REPO}:/var/www
    links:
      - php

  mariadb:
    container_name: mariadb.plb
    image: mariadb:10.3.9
    volumes:
        - /tmp/plb_data/:/var/lib/mysql
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_USER_PW}
