# PHP 
#
# VERSION    7.4.10

FROM php:7.4.10-fpm

# Install required apps : git, zip, wget, zcat, mariadb and ldap libraries
RUN apt-get update && apt-get install -y zip wget git mariadb-client apt-utils libldb-dev libldap2-dev curl unixodbc-dev unixodbc-bin unixodbc

# Install required extensions for php
RUN docker-php-ext-install calendar ldap json pdo pdo_mysql mysqli && docker-php-ext-enable json ldap pdo pdo_mysql mysqli 

# Install composer
ADD ./docker/get_composer.sh .
RUN ./get_composer.sh
RUN mv composer.phar /usr/bin/composer
CMD: ['./clean-install.sh']
